### ISSUE TITLE
NTR: occupies/is occupied by or lives at

### ISSUE THREAD

**Issue by ramonawalls** [oborel/obo-relations#113]
occupies:

def: A relation between an organismal entity OE and a site S during some time interval T. OE occupies S at T if OE lives at S throughout T.

domain: organismal entity (from PCO), range: site

inverse of --

is occupied by:

def: A relation between a site S and an organismal entity OE during some time interval T. OE occupies S at T if OE lives at S throughout T.

domain: site, range: organismal entity (from PCO)

**Comment by cmungall** [comment]
I think the label is too generic for the definition.

You'd also need to define lives-at. In fact maybe that is the relation 
you want? Though I would call it lives-at-site if you really want to 
restrict the range to sites.

Can you give some examples of living-at? How much of T does the organism 
have to spend at the site to live there? Is it determined by particular 
activities performed at the site? For example, sleeping/rest?

How would you use this for, say, a salmon?

**Comment by rlwalls2008** [comment]
@cmungall, re. site as range, I don't really know if it should be site or spatial entity. In fact, a site is defined as a 3 dimensional spatial entity, but it is not all that clear when a 3-d spatial area is or is not a site. So maybe it is safer to just use spatial entity.

Here are some examples of living at/occupying that we need for PCO:
Juan and Maria live in the same apartment and share their meals.
A cuckoo chick and a chick of the host species are reared in the same nest.
A population of coyotes lives in the same ecosystem as a population of rabbits.

There are of course a ton of gray areas, which is why I want to leave this sort of vague about how much of time T an organism has to spend in an area to live there.

**Comment by pbuttigieg** [comment]
>Here are some examples of living at/occupying that we need for PCO:
Juan and Maria live in the same apartment and share their meals.
A cuckoo chick and a chick of the host species are reared in the same nest.
A population of coyotes lives in the same ecosystem as a population of rabbits.

These all sound like sites (relativised by the apartment walls, the nest boundaries, or the ecosystem extent) - spatial regions are a bit more absolute and not really relevant to most spatial thinking done by humans.

>There are of course a ton of gray areas, which is why I want to leave this sort of vague about how much of time T an organism has to spend in an area to live there. 

If you mean that the organism is simply alive in a given site, unless the organism is moving really, really fast (at a speed which would probably kill it) then this probably means something very close to `organism located_in some site`. If it's more than that, it may be approaching `habitat` semantics. Of course, you could be more granular and identify a `biological process` (or an ecological one) that must be completed before the organism can be said to "live" at a site in a particular way.

**Comment by rlwalls2008** [comment]
@pbuttigieg, ecosystem was  one that I was uncertain with. Also, what if someone just provides a bounding box on the surface of the earth, is that still a site? We are using site this way in BCO, but I'm not certain if it is correct.

Re. located, yes, at some level, they just need to be alive in the same site, at a very high level. Of course we will want to define more specific meanings of located in that correspond to "living" for different taxa or applications. I guess for this high level class, it is sufficient to say that two organisms or populations are alive at the same site at some t, because t will have to be long enough to allow for some interaction, as the entities in an "ecological community" must be interacting because of the relation inherited from the parent "community".

I'm think for now I will define the PCO class using located in, and then we can figure out if we need a more specific relation.

**Comment by rlwalls2008** [comment]
Lives at could be a subclass of located in that has as domain an organismal entity.

**Comment by mark-jensen** [comment]
> Also, what if someone just provides a bounding box on the surface of the earth, is that still a site? We are using site this way in BCO, but I'm not certain if it is correct.

I think it's correct. If I take a bounding box to be along the lines of a "geospatial region", regardless of how the boundaries are defined, potentially even immaterial ones, it would still be a `site`.

**Comment by nlharris** [comment]
So is this done?

**Comment by ramonawalls** [comment]
@nlharris A new relation was never added, but we have been living without it for so long, I hardly notice its absence. I think it would be safe to close this, and I can reopen if a pressing use case comes up again.

The original use case for this relation was to define PCO:household, which is a group of people living in the same dwelling. Not having a relation for lives in does not seem to have been a blocker.

**Comment by nlharris** [comment]
Ok, closing.
