### ISSUE TITLE
Import "organismal entity" from PCO and "site" from BFO

### ISSUE THREAD

**Issue by ramonawalls** [oborel/obo-relations#114]
I would like to use these classes as domain and range for the new properties "occpuies" and "is occupied by". We could in theory use independent continuant instead of site.

Organismal entity is a union class in PCO that is CARO:organism or virus or viroid OR PCO:collection of organisms.

@cmungall, I have edit rights to RO, so I can add new properties, but I don't know how imports are handled, and i don't want to mess up the production process by adding new imported classes.

**Comment by rlwalls2008** [comment]
We could be more general and use independent continuant instead of site (so that an organism can occupy a material entity or a site). Using site makes things more complicated, but I think more precise. For example, to say that a PCO:household occupies a ENVO:human dwelling (which is a material entity), we have to actually say that the household occupies some site that is part of some human dwelling.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
