### ISSUE TITLE
habitat_for or engineer relation

### ISSUE THREAD

**Issue by diatomsRcool** [oborel/obo-relations#135]
I need a relation to describe the interaction between an organism that provides habitat for another organism. This could be a tree serving as habitat for another organism that lives in or on it. It could also be an ecosystem engineer, like a beaver that makes habitat for other organisms through its actions. Thoughts?

**Comment by pbuttigieg** [comment]
EnvO's environmental feature is intended for something like this : you'd
import organism X into EnvO, create "X environment " (to be clear that
you're talking about an environment provided by an organism rather than the
organism itself) which is determined_by organism X, and then use that class
and a relation like located_in to place organism Y. A bit long winded,
perhaps we can streamline this.

If you definitely mean habitat, you can create an "X habitat " (with org X)
in EnvO's habitat branch and then use 'overlaps ' relations with the
environments or environmental features which constitute it. You can then
use a relation like has_habitat between X and "X habitat ", updating the
links between the latter and environments as knowledge increases.


On 20 Dec 2016 21:33, "diatomsRcool" <notifications@github.com> wrote:

I need a relation to describe the interaction between an organism that
provides habitat for another organism. This could be a tree serving as
habitat for another organism that lives in or on it. It could also be an
ecosystem engineer, like a beaver that makes habitat for other organisms
through its actions. Thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/oborel/obo-relations/issues/135>, or mute the thread

**Comment by diatomsRcool** [comment]
I understand what you mean, but I need something for globi. Let's take a specific example. A prairie dog digs a burrow that is then used by a snake. I want to include this relationship in globi which takes data in the form of sourceTaxon:interactionType:targetTaxon. According to your advice above, I could import prairie dog into Envo and then create priarie dog burrow as an environment in envo. Then say that a prairie dog burrow is determined_by a prairie dog. Then say that the snake is located in the prairie dog burrow. Makes sense, but how to I translate that into the data format needed in globi?
The other example is a beaver building a dam that creates a wetland, which is habitat for a frog. I can import beaver into envo. Should I create beaver dam and beaver dam wetland into envo? Would I need to indicate that the beaver dam wetland is determined_by the beaver dam which is determined_by the beaver? I can say that the frog is located in the beaver dam wetland, but not the beaver dam itself. I am still left with needing a way to include this in globi.
Does that make sense?

**Comment by diatomsRcool** [comment]
Added a term for creating habitat to the relations ontology
