### ISSUE TITLE
grows_on

### ISSUE THREAD

**Issue by diatomsRcool** [oborel/obo-relations#137]
I need a term to represent an organism growing/living on another organism, such as a lichen growing on a tree. Thoughts?

**Comment by cmungall** [comment]
Should this be neutral w.r.t who benefits?

**Comment by diatomsRcool** [comment]
Good question. The data sets I am working with are not implying either way, merely reporting an observation. So, I would think it should be neutral.

**Comment by pbuttigieg** [comment]
There was the eco-subset that we nucleated at NCEAS. These relations will
fall therein, right? Coordinate with GloBI?
Sounds a bit like a shorthand of some growth process and attachment or
embedding.

On 20 Dec 2016 22:08, "diatomsRcool" <notifications@github.com> wrote:

Good question. The data sets I am working with are not implying either way,
merely reporting an observation. So, I would think it should be neutral.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/oborel/obo-relations/issues/137#issuecomment-268360065>,
or mute the thread

**Comment by dosumis** [comment]
Take a look at relations under ['participates in biotic-biotic interaction with'](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002574).  I suspect this class may work

Perhaps [symbiotically interacts with](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002440) or request a sub-relation specifying an epiphytic relationship?.  Note that 'symbiotically interacts with' is agnostic wrt whether one partner gains from the other (see cognate GO term:  http://www.ontobee.org/ontology/GO?iri=http://purl.obolibrary.org/obo/GO_0044403)

**Comment by pbuttigieg** [comment]
+1 for epiphytic relations ; more specificity will make it much easier to
interface with ecological data
