### ISSUE TITLE
A new relation "has substance added" perhaps?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [oborel/obo-relations#143]
I was looking for a relation similar to RO's "has part > has active ingredient" for the FoodOn ontology.  However I need something less confident.  The ingredient is not necessarily active, and may not even exist any more in the entity it was added to.  So how about a "has substance added" relation:
 
definition "'has substance added' is a relation existing between a (physical) entity and a substance in which the entity has had the substance added to it at some point in time."

The relation X 'has substance added' some Y doesn't imply that X still has Y in any detectable fashion subsequent to the addition.  Water in dehydrated food or ice cubes are good examples, as is food that undergoes chemical transformation.  This definition should encompass recipe ingredients.  (One could even annotate such relations with measures, process timings, methods etc. to create a recipe, or other process description.)

I had named it "has material added" previously, but then there are cases where gases are added, and "substance" covers gas.

I suppose, likewise, a "has substance removed" would be generically useful too, e.g. egg without the yolk.

Thoughts?

**Comment by cmungall** [comment]
Sounds good - do you want an ID range to do PRs?

**Comment by Public-Health-Bioinformatics** [comment]
Sure! (I don't expect to be tinkering that much though!)

**Comment by Public-Health-Bioinformatics** [comment]
Ok I've finished this as an import file.  I added one other relation: "immersed in" too.  Shall I just attach, or send it by email?

**Comment by cmungall** [comment]
NSWYM by import file...

Do you want to just go for a pull request?

**Comment by Public-Health-Bioinformatics** [comment]
Oh, over at ENVO they were talking about all new items to come in by an import file for easy isolation and review so I thought that might be preferable; but I'm fine with doing a pull request directly then with additions right in ro.owl .

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I've added a pull request.

**Comment by ddooley** [comment]
So an update on this and a related request to discuss.  We are using "has substance added" with respect to food especially to describe contaminants that come in from packaging, or other sources of contamination etc.  

In FoodOn, we currently have "has ingredient" and "has defining ingredient" relations.  Is RO interested in picking these up or would they remain in FoodOn because the domain and range restrictions point to a FoodOn class?  I'm updating the definitions in FoodOn, but here they are provisionally, below.

label: "has ingredient"
definition "A relation attaching between a food material and another food material that has been added to it at some point in its history."@en

label: "has defining ingredient"
definition "A 'has ingredient' relation which points to a food material that the subject food material would primarily be categorized by."
elucidation: "A defining ingredient does not imply any percentage of weight or volume with respect to the food material.  A food may have more than one defining ingredient."@en
Example of usage: "bean soup has a defining ingredient of beans."

**Comment by nlharris** [comment]
Can this issue be closed?
(I have not tried to make bean soup without beans, but I did once forget to put mushrooms in the mushroom barley soup.)

**Comment by ddooley** [comment]
Ah, yes - relation has been added.

**Comment by ddooley** [comment]
And FoodOn can keep "has ingredient" and "has defining ingredient"

**Comment by nlharris** [comment]
Great, so we can close?

**Comment by ddooley** [comment]
yes

**Comment by ddooley** [comment]
Though it seems "has substance added" has curation status of "requires discussion"

**Comment by cmungall** [comment]
I think we need to abandon has-curation-status, it's not used consistently
and meaningfully. Instead have links to tickets.

**Comment by nlharris** [comment]
> I think we need to abandon has-curation-status, it's not used consistently and meaningfully. Instead have links to tickets.

Should I make a ticket for "abandon has-curation-status"?

**Comment by cmungall** [comment]
yes!
