### ISSUE TITLE
'capable of' o 'in taxon' -> 'in taxon' causes unsatisfiable classes

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#169]
Doing some experiments with [go-plus](http://purl.obolibrary.org/obo/go/extensions/go-plus.owl) and [Uberon ext](http://purl.obolibrary.org/obo/uberon/ext.owl) imported together. With current releases you end up with 28 unsatisfiable classes. They all go away if you remove the property chain `'capable of' o 'in taxon' -> 'in taxon'`. I attached an example explanation. The usage of this property (primarily in CL?) seems like more of a "some-some" rather than "all-some" notion. If that is true it makes the property chain too strong.

<img width="1364" alt="unsatisfiable" src="https://cloud.githubusercontent.com/assets/210210/26749583/07b9528a-47dc-11e7-9c5a-01ba682c25db.png">

**Comment by cmungall** [comment]
Thanks, this is indeed a mistake, not all mesenchymal cells are capable of cardiac muscle cell differentiation, this axiom is wrong (as well as kind of useless).

There are many valid usages in CL (e.g. the capable-of secretion patterned ones) but this isn't one. If you have a list handy we should eliminate. But really the larger problem here was that this wasn't caught earlier, because cl imports a lighter version of uberon+go such that you don't follow the cl->go->uberon->taxon path)

**Comment by balhoff** [comment]
> Thanks, this is indeed a mistake, not all mesenchymal cells are capable of cardiac muscle cell differentiation, this axiom is wrong (as well as kind of useless).

Okay, good to know.

> There are many valid usages in CL (e.g. the capable-of secretion patterned ones) but this isn't one. If you have a list handy we should eliminate. 

Great, I'll make a list.

> But really the larger problem here was that this wasn't caught earlier, because cl imports a lighter version of uberon+go such that you don't follow the cl->go->uberon->taxon path)

Yep, this is what I'm interested in.

**Comment by balhoff** [comment]
This came down to two relationships for 'mesenchymal stem cell': https://github.com/obophenotype/cell-ontology/issues/474
