### ISSUE TITLE
treatment of regulates relations and their parents

### ISSUE THREAD

**Issue by phismith** [oborel/obo-relations#235]
The GO regulates relations are part of a hierarchy, illustrated here:
+ related via dependence to
   + causally related to
       + causal relation between processes
              + causally upstream of or within
                 + causally upstream of
                     + causally upstream of, positive effect
                     + causally upstream of, negative effect
                     + immediately causally upstream of
                     + transitively provides input for
                     - regulates (processual)
                           - has effector activity
                           + negatively regulates
                           + positively regulates
                           + directly regulates
 
 
An example is as follows: 
ObjectProperty: related via dependence to
Term IRI: http://purl.obolibrary.org/obo/RO_0002609
Definition: A relationship that holds between two entities, where the relationship holds based on the presence or absence of statistical dependence relationship. The entities may be statistical variables, or they may be other kinds of entities such as diseases, chemical entities or processes.
There would seem to be a number of problems with this definition, including:
 
1. it defines 'dependence relationship' in terms of 'statistical dependence relationship' which looks circular
2. it allows a relationship of dependence to hold in virtue of the absence of a statistical dependence relationship, which seems odd.
3. what, from the OBO Foundry perspective, is a statistical variable? is it an entity?

**Comment by dosumis** [comment]
> ObjectProperty: related via dependence to
> Term IRI: http://purl.obolibrary.org/obo/RO_0002609
> Definition: A relationship that holds between two entities, where the relationship holds based on the presence or absence of statistical dependence relationship. The entities may be statistical variables, or they may be other kinds of entities such as diseases, chemical entities or processes.
> There would seem to be a number of problems with this definition, including:

> it defines 'dependence relationship' in terms of 'statistical dependence relationship' which looks circular
> it allows a relationship of dependence to hold in virtue of the absence of a statistical dependence relationship, which seems odd.
> what, from the OBO Foundry perspective, is a statistical variable? is it an entity?

I'm suspicious of the reference to statistics in this definition too.  I might be wrong, but it seems to tangle assertions about the world with evidence that supports those assertions.  I'm pretty sure that this objectProperty is not directly used in assertions or queries,  but is designed to group a wide range of subProperties that are directly used.  The subProperties used by GO are, I think, reasonably well thought through and do useful work in reasoning.  

@cmungall - are there any subProperties of 'related via dependence to' that are designed to relate 'statistical variables? If so, can you provide examples of their usage?

**Comment by cmungall** [comment]
Thanks for the ticket @phismith and comments @dosumis 

I think this is just a mistake. 

This is one of our grouping relations. These will have the following text in the curator note field: "Do not use this relation directly. It is intended as a grouping for a diverse set of relations, all involving cause and effect." (we should better document these, and perhaps make an antislim for them, so they can be excluded). The grouping relations don't do any real logical or semantic work, they are just unions that exist primarily for organizational and browsing purposes. 

The intent here was to group a broad family of causal relations with correlation relations. The latter needs some work, it includes relations that are useful for when you want to say that a gene is a marker for a disease, but may not be directly causally linked. For these I think it would be more attractive to frame this causally, but in terms of an additional causal factor (aka hidden variable). But we also have relations for where we may want to specify a correlation, where we don't know whether this correlation is random, due to a direct causal link, or due to a confounder.

In any case, it may be better to completely decouple these two sets of relations.

**Comment by dosumis** [comment]
> it may be better to completely decouple these two sets of relations.
+1

**Comment by cmungall** [comment]
OK, my fix here: https://github.com/oborel/obo-relations/pull/237 is to obsolete the offending "related via dependence to"
