### ISSUE TITLE
Make enables/enabled_by subproperties of participates in/has participant

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#249]
Following on from #244 

cc GO editors @vanaukenk @ukemi @balhoff

**Comment by LEHunter** [comment]
I don't understand how to tell whether a participant "enables" a process.  We need a 'differentia' for this relation if it is to be useful.

In a biochemical reactions, all of the participants are required, or the process will not occur (or at least not occur at the same rate).  Having a function inhere in the participant doesn't seem to be helpful, as all participants in a process are realizing some function(s), that is what it means to participate.

It seems straightforward to me to define inputs, outputs, and 'participants that are unchanged' by a reaction.  However, distinguishing "enablers" (or, for that matter, "agents" vs. "patients") in this context seems to me a loose convention, rather than a well-defined distinction.  I recognize that biologists would distinguish between (say) water molecules and a catalyst this way, but both are necessary participants and both are (generally) unchanged by a reaction.  

A distinction I could imagine supporting here is between ubiquitous participants (those that participate in many reactions, e.g. water) versus specific participants (e.g. a catalyst) that participate in only a few processes.  This seems to me why the water molecules are called an "aqueous environment" rather than an enabling participant. 

i also admit I have no idea exactly where to draw the line between 'many' and 'few'...

**Comment by ukemi** [comment]
I suspect this proposal might also lead to further issues deriving annotations from GO-CAM models. Currently x-metabolic process is defined as ''metabolic process' and ('has participant' some x)". Inference of participation in property chains is already causing some issues when specifically annotating proteins.
https://github.com/geneontology/minerva/issues/197

**Comment by cmungall** [comment]
Currently being discussed at GO geneva meeting @vanaukenk @ukemi @balhoff @goodb @pgaudet
