### ISSUE TITLE
Create geneweaver subset for X-gene relations

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#257]
geneweaver currently annotates gene sets with ontology classes - e.g. a gene set for a GO process or a phenotype or a disease. One problem here is this is ambiguous as to the relationship between the gene and the term. What does it mean to be a disease gene set?

@ukemi is exploring adding relationships to geneweaver. What would help if there was a subset of RO created for anything that could be used as a X-to-gene relationship, in particular for diseases.

This relates to work @mbrush has been doing on the predicate set for the biolink model in the NCATS Translator project.

**Comment by ukemi** [comment]
Looking a little closer at 'over-expressed in' (RO:0002245), the range is an independent continuant, so it won't work for a disease, since a disposition is a specifically dependent continuant. So what is the relationship between an over- under-expressed gene and a disease or a phenotype?

**Comment by cmungall** [comment]
One of the challenges here is that a natural biological upper level ontology doesn't necessarily align with BFO. diseases and phenotypes are clearly very alike, to the extent that HP has seemingly identical classes to MONDO, DO or NCIT (your breast carcinoma example) (I have been discussing this with @mbrush ). We've been putting in stricter D+R constraints in #261 and we have been using the expression `disease or phenotype` a lot which is IMHO a little unsatisfactory.

OK, let's look at your example, I would model this in granular terms for a disease as:

`(disease) realized_in (disease process) causally upstream of, {+,-} effect (gene expression)`, where the gene expression node occurs-in some (tissue) and has-input some (gene).

(this may be an overstatement as perhaps for some gene sets the overexpression may be causative or merely correlated?)

So if we have a shortcut relation for the + and - forms that should serve your purposes?

**Comment by ukemi** [comment]
I think the inverse relation would. I was thinking that a gene sets would have member genes and the descriptions would be similar to 'A gene in this set property-ontology term'. See my GO example above. I also think phenotype examples for MP and HPO are reasonably straightforward. Since the curation stream at MGI captures genes that contribute to phenotypes when mutated, I think we could use 'has phenotype' as a valid relation. I assume that HPO has a similar paradigm. For the tissue example above, I assume that a tumor (or metastasis) is included? What ontology represents those material entities?

Maybe if we have a bit of spare time in Montreal, we can look at some specific gene sets? We will want to go beyond just cancer. @echesler and her group curate a lot of addiction- and behavior-related sets. We'd also be interested in some default relations that we could use for initial population, a generic relation between a continuant (gene) and any ontology term that we have used in the past.

The causal versus correlative point is well-taken. One of our use cases is to hypothesize about causal from correlated using the GW tool suite. Many of our sets are correlated.

**Comment by ukemi** [comment]
Trying to tag @judyblake again.

**Comment by nlharris** [comment]
@sierra-moxon since this was tagged "biolink" (albeit by past-me, who may have just been guessing) do you happen to know if this can be closed?

**Comment by erichbaker** [comment]
Yes. I think so

Typos and randomly weird text courtesy of my iPhone
