### ISSUE TITLE
Link from relations to all patterns that use that relations

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#314]
This could be automatically mined from a registry of robot and dosdp patterns and added into RO as annotation assertions.

Should we seed the registry in this repo or in the obo repo? I think rather than indexing each pattern we index the URL of the folder and traverse files in the directory? cc @jamesaoverton @matentzn @dosumis

**Comment by matentzn** [comment]
Good idea. Not sure how robust your solution will be to change (pattern directories moving around etc). Instead of hardcoding the pattern location, have a DOSDP pattern for the annotation assertion, generating the pattern tsv from purls pointing to github directories (might require looking into the yaml files to get the purl); would be okay I think, and then merging the resulting definitions.owl into RO.

**Comment by cmungall** [comment]
So are you suggesting that the originating ontology would annotate their classes with the DP? I think that would be best, we could just sparql query in ontobee. However, I think it will be a while before we achieve this so as a first pass we need some kind of registry as there are growing number of ontologies using yamls + we need to track and combine.

I like the ideas of merging the definitions.owl

Working with @phitzler @handemcginty @balhoff on abstraction of DPs above existing domain-specific ones. E.g. EnvO and GO process classes use the same "meta-pattern" but different yamls due to need to concretize in terms of classes from those ontologies (what I called "meta-pattern" may be more like what Pascal calls a pattern, and out patterns are more like macros or templates...). As both use similar relations grouping patterns by relation is a good start.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
