### ISSUE TITLE
Term request - frequency_in_condition

### ISSUE THREAD

**Issue by kshefchek** [oborel/obo-relations#332]
It would be useful to have a relationship to link an instance of a phenotype to the frequency seen in a cohort of patients diagnosed with a condition.  This could be either an object property (eg subClasses of https://hpo.jax.org/app/browse/term/HP:0040279), or a datatype property.

**Comment by cmungall** [comment]
One way to model this is using a basic population size property. E.g. pop1 is the cohort, pop2 is the subset of the cohort with the phenotype. If you know the size of each you have the frequency.

This would obviously be very verbose so I think having a shortcut property would be useful here. I think there is also a use case for attaching the property to the cohort->phenotype edge, or more generally to any edge.

E.g.

```
?s ?p ?o << ro:subject_has_object_with_frequency 0.5>>
```

 (see [this post](https://douroucouli.wordpress.com/2019/07/11/proposed-strategy-for-semantics-in-rdf-and-property-graphs/) ).

**Comment by kshefchek** [comment]
I prefer the latter but can work with either.  I think in most cases of phenotype-disease from the HPO this is a qualitative value.

**Comment by dosumis** [comment]
A generic way to model phenotype penetrance would be v.useful.  This is tricky to do well in OWL if we want to be able to roll penetrance into classes. For lethality modelling I used a reified data property 'mortality rate' as, for the pattern I used, a generic penetrance data property => problems with co-reference resolution.  For annotation I prefer the edge tagging approach as easy to use this for filtering edges.  Can we call this has_penetrance?  It would also be useful to have a way to make qualitative assertions of penetrance (low, medium, high).  Makes sense to me to use edge tagging for this too.

**Comment by mah11** [comment]
In PomBase FYPO phenotype annotations, penetrance is one of the things for which we use (traditional, pre-GO-CAM) GO-style annotation extensions. The relation is indeed _has_penetrance_, and the range accepts numerical values (as percents) or qualitative values selected from a tiny in-house CV (low, medium, high, full/complete, variable).

I'm not familiar with the "edge tagging" jargon, so I don't know if our use of extensions is the same thing or similar.

If I understand "roll penetrance into classes" correctly, we don't want to do it. We want penetrance associated with annotations, and not by using different ontology classes for different penetrance observations.

(Minor aside: it would not have occurred to me to use "frequency" to refer to incidence or penetrance, but that may be because I've spent so many years steeped in single-celled organisms ...)

**Comment by kshefchek** [comment]
I'm not sure we should conflate penetrance with disease phenotype frequency from the HPO, although these might be the same value in mendelian disorders.  Perhaps two new properties are needed?

**Comment by cmungall** [comment]
Yes, might need a hierarchy of data props.

Can we have a more descriptive name 'has genetic penetrance' - ugly I know
but RO has a broad community not just geneticists...

**Comment by kshefchek** [comment]
checking if this is anyone's radar, it would be good to get rid of our fake IRI's in monarch

**Comment by dosumis** [comment]
> checking if this is anyone's radar, it would be good to get rid of our fake IRI's in monarch
> 
Looking over this again, I think it makes sense to have a generic way to record frequency in a population by tagging phenotype assertions (given that penetrance apparently doesn’t work for non-mendelian traits (?)).   This could be via direct tagging of edges with a has_frequency  AP,  but  if we need to be able to record something about cohort/population  for which frequency is recorded, then perhaps better to attach an OWL:individual to edge and attach assertions about frequency and population to that individual - something like we do for provenance.  Or  - I  guess we could allow for both patterns.

**Comment by nlharris** [comment]
What is the status of this?
