### ISSUE TITLE
inheres in and symmetric relational qualities

### ISSUE THREAD

**Issue by matentzn** [oborel/obo-relations#341]
There has been some discussion about inheres in being functional, but I keep wondering whether this is the way to go. My current problem is the representation of symmetric relational qualities, like `fused with` or `decreased distance between`. If the nose is fused with the eye, why should the phenotype only classify under abnormal eye OR abnormal nose? Shouldnt it be both? I think that using towards for _directional_ relational quality modelling is fine: increased resistance of cell towards chemical; but I think the not so super small number of symmetric relational qualities should also be modelled appropriately. @cmungall @dosumis @balhoff 

Maybe lets use this as an opportunity to review the arguments for inheres in being functional. The only email trail I could find was:

@cmungall 
```
We should never have something inhering in two entities.
This has consequences for the RO PR if we want to make it a super-property of existing properties
```

and @jamesaoverton 
```
I agree
```

Lets elaborate a bit perhaps :P

**Comment by balhoff** [comment]
@LarsVogt has been asking about exactly this as well.

**Comment by matentzn** [comment]
He is the one that brought it again to my attention! and I have faced it before, but I just wanted to postpone it until we had to make a choice!

**Comment by LarsVogt** [comment]
We (Jim, Hong, ìstván, Matt, Ramona, myself and others) are currently working on a set of model patterns for a semantic data model for Phenotype Knowledge Graphs (phenotype descriptions represented as instance-based RDF knowledge graphs). When looking at relational qualities, we soon realized that they come in two types: symmetrical and directional (we called them asymmetrical, but directional is a much better term). Whereas modelling the directional relational properties such as _proportion of water in a given anatomical structure_ was straight forward (using ro:inheresIn and ro:towards), we found that using the same pattern for modelling directional relational properties such as _adjacency of two structures_ or _distance between two structures_ is not very elegant, because the directionality implicit in the model is not reflected by the relational quality being modeled.  Whereas one could certainly model the respective relational qualities using "detours", we would prefer to model them directly using, e.g., a non-functional property 'relationalQualityOf' / 'hasRelationalQuality'. 

I know, we could, e.g., use ro:adjacentTo for adjacency between two structure X and Y, but I always prefer to minimize the number of properties and since adjacency is not transitive, we do not need to model it using a property and could instead model it using a class 'adjacency':
S:instance_structureX   P:hasRelationalQuality   O:instance_adjacency 
S:instance_structureY   P:hasRelationalQuality   O:instance_adjacency 

We could model the distance between two structures X and Y as a quality of a line, but that would require creating an instance of a line for every distance documented in a given phenotype knowledge graph AND we would have to define each such line as the distance between two structures. I would prefer to model it as: 
S:instance_structureX   P:hasRelationalQuality   O:instance_distance
S:instance_structureY   P:hasRelationalQuality   O:instance_distance

Following this approach, we would require only four basic patterns for modelling qualities of anatomical structures (ignoring measurements):

1) quality (e.g. shape): 
S:instance_structureX   P:hasQuality   O:instance_quality

3) symmetrical relational quality (e.g. distance, adjacency):
S:instance_structureX   P:hasRelationalQuality   O:instance_relationalQuality
S:instance_structureY   P:hasRelationalQuality   O:instance_relationalQuality

2) 'non-transitive' directional relational quality (proportion of water):
S:instance_structureX            P:bearerOf   O:instance_relationalQuality
S:instance_relationalQuality   P:towards    O:instance_structureY
(this general pattern could be used for modelling all kinds of relative positional relations such as anteriorTo, dorsalTo, etc, but also X boundaryOf Y - using this pattern instead of specific properties would significantly reduce the amount of properties required for modelling phenotypes)

4) 'transitive' directional relational quality (e.g. surrounded by):
S:instance_structureX   P:surroundedBy   O:instance_structureY

**Comment by matentzn** [comment]
I think since we are all talking now, it makes sence to try to align all these ways to model.

 > we would prefer to model them directly using, e.g., a non-functional property 'relationalQualityOf' / 'hasRelationalQuality'. 

So are you saying that inheres in should only be used with unary qualities like increased size, increased

> I know, we could, e.g., use ro:adjacentTo for adjacency between two structure X and Y, but I always prefer to minimize the number of properties and since adjacency is not transitive, we do not need to model it using a property and could instead model it using a class 'adjacency':
S:instance_structureX P:hasRelationalQuality O:instance_adjacency
S:instance_structureY P:hasRelationalQuality O:instance_adjacency

If we go down that road, I agree your modelling is preferable. Not yet sure about the road. I first need to be convinced again about not using `inheres in` instead of `has_relational_quality`.

> quality (e.g. shape):
S:instance_structureX P:hasQuality O:instance_quality

Why is this not `bearer of`?

> symmetrical relational quality (e.g. distance, adjacency):
S:instance_structureX P:hasRelationalQuality O:instance_relationalQuality
S:instance_structureY P:hasRelationalQuality O:instance_relationalQuality

Makes sense, if we go there..

> 'non-transitive' directional relational quality (proportion of water):
S:instance_structureX P:bearerOf O:instance_relationalQuality
S:instance_relationalQuality P:towards O:instance_structureY

Assuming `bearer of` is the inverse of `inheres in`, I am happy with that. This is in any case what we do.

> 'transitive' directional relational quality (e.g. surrounded by):
S:instance_structureX P:surroundedBy O:instance_structureY

Hmmmm, never thought about that... Seems important to get this right; @dosumis ?

**Comment by cmungall** [comment]
My current intuition is that when we use RQs we are trying to get PATO to do too much work, things get unintuitive. Most people do not understand RQs and get confused quickly, especially when we take into account the implicit relata in all increased/decreased terms

In all cases, the RQ can be modeled as a simple single-bearer Q with the relational work pushed to an IC or process.

E.g the horrible 'fused with' (which to compound confusion, sounds like it should be in RO). Here there is a fusion process. We can use standard process DPs. 

Same with distance between. It's the length of a line that connects two points. We have these DPs in Uberon already. We don't want two ways to model the same thing.

**Comment by dosumis** [comment]
I suspect that in many, perhaps the majority of cases fused bone terminal phenotypes are not a  result of the same process as bone fusion during normal development(e.g. of cranial bones).  For example, many are rather the result of defects in pattern specification.   Using  the BP will therefore servce to group phenotypes with completely different molecular developmenal bases.

I know you're not keen on making RQs into relations - but maybe we should make an exception with fused_with and make a symmetrical RO relation.

**Comment by dosumis** [comment]
Broader context:  inheres_in  needs to remain  functional if we are to use the towards pattern and maintain  proper co-reference.  Maybe we could consider making all symmetrical RQ -> R ?


 symmetrical RQs become Rs, allowing inheres_in to remain functional

**Comment by matentzn** [comment]
@LarsVogt do you have any idea how many symmetric relational qualities there are in PATO?
@dosumis do you think it makes sense to actually group directional relational, symmetric relational and non-relational properties in PATO under respective classes?

It feels a bit 'hacky' to introduce relations for symmetric relational qualities and not for directional relational qualities... What is the advantage of that over @LarsVogt suggestion of using a different relation altogether? If we knew how many relational qualities there are altogether, maybe we could assess how hard it would be to turn ALL RQs into relations?

> My current intuition is that when we use RQs we are trying to get PATO to do too much work, things get unintuitive. Most people do not understand RQs and get confused quickly, especially when we take into account the implicit relata in all increased/decreased terms.

This argument needs to be operationalised if we want to really use it for making a decision :P. Thats why we use patterns: to abstract away from this for the curators, no? So, usability lies in the patterns, and here we need to worry about representational adequacy, not usability.

> In all cases, the RQ can be modeled as a simple single-bearer Q with the relational work pushed to an IC or process.

I dont know whether this is true, maybe. There is not always a line to refer to when denoting increased distance, for example.

**Comment by matentzn** [comment]
But: I am still open for the idea of turning only symmetric RQs into RO relations.. We need to check that the semantics work as intended (need to actually look this over -> inheres in (nose fused with eye) should be also under abnormal eye).

**Comment by balhoff** [comment]
Not necessarily abnormal. We use ‘fused with’ for descriptive phenotypes.

**Comment by matentzn** [comment]
sorry, I meant:

` inheres in (nose fused with eye) and has modifier some abnormal` under `abnormal eye`

**Comment by cmungall** [comment]
Good point, it could be inadvisable to use a GO process here. This is maybe
too 'interesting' a case to use as exemplar, since we may not know if this
is due to a fusion process or a failure of separation or something else.
The point is that we could use some of kind of IC or P class, even
something like 'fused structure' (sensu material entity)

**Comment by LarsVogt** [comment]
ro currently has over 50 properties with a label following the pattern "in [XXX] relationship with". I did not look into them in detail but many of them seem to refer to symmetrical RQ and could be covered by the same or an analogues pattern as the one used for qualities, modeling the symmetrical RQ as classes. The advantage of modeling RQ as classes is also that it is easier, I think, to classify them as classes than as properties, isn't it?

**Comment by cmungall** [comment]
not totally following, sorry

I see the following 2

RO:0002375 ! in branching relationship with

RO:0002602 ! in approximate one to one relationship with

**Comment by LarsVogt** [comment]
I looked at it through the ontology lookup service (https://www.ebi.ac.uk/ols/ontologies/ro) and there several object properties are listed with labels following the pattern "in [...] relationship with', e.g. 'in apomorphy relationship with' (RO:HOM0000042)

**Comment by cmungall** [comment]
Ah yes.. sorry it looks like we are missing documentation from the RO
guide. This is just an automatic translation of classes from HOM

**Comment by nlharris** [comment]
What is the status of this? Is there more work to be done (add something to documentation?)?

**Comment by matentzn** [comment]
This is important and not solved. We will revisit this when we work out the Upheno relations properly, which will be at some time early next year.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
