### ISSUE TITLE
Add biotic interaction terms from parasite tracker project

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#343]
@jhpoelen expects more terms coming from parasite tracker project. We need to determine

 1. what is the most efficient way for this group to provide requests for changes or new terms
 2. how is this to be coordinated with ecocore (@diatomsRcool @pbuttigieg )
 3. are we adequately resourced?

For 1, we need more info (from @jhpoelen?). If we are provided with a tsv we should be able to script the addition. However a likely scenario is that we will need a lot of back and forth to get definitions that meet our standards etc. The ideal scenario is that someone comes in and makes PRs but this takes training.

For 2, will we be shadowing anything in ecocore? Ideally all interaction relations should shadow processes

For 3, we want to avoid disappointment. We don't have RO funding but smaller requests can be handled easily. Note we have other outstanding tickets in this area #74 #227 - I am not sure if anyone in any of your projects is funded to do this @diatomsRcool ?

**Comment by diatomsRcool** [comment]
All good questions. I am still wrestling with parasite and host in ecocore, but probably because I just have to make a decision and do something. I'm not familiar with the parasite tracker project, so I would need to see some terms before knowing for sure what to do with them. Any relationships should go in RO, of course, but if we want to talk about a process or an entity it should go in either ecocore or PCO - as you know. I do not currently have funding to support ecocore.

**Comment by jhpoelen** [comment]
@cmungall @diatomsRcool I am trying to convince TPT folks to establish a biotic association terms working group. I imagine this group, once established, will review existing terms and suggest updates and/or new terms.

If someone can spare some time to show me how to prepare a pull request to update RO or add new terms, then I can record and share the process with TPT folks in specific and GloBI folks in general. I can also figure it out myself, but that would probably take much longer. 

@cmungall and @diatomsRcool Would you be ok to help with this in addition to reviewing the occasional RO pull request?  

fyi - @seltmann @zaspelj @neilcobb

**Comment by diatomsRcool** [comment]
@cmungall is more knowledgeable about RO PR processes than I, but I am available to review PRs as needed.

**Comment by cmungall** [comment]
I expected we want to make a new workflow here such that the terms can be added as TSVs, rather than having Jorrit and others do these in Protege

**Comment by neilcobb** [comment]
I struggle with terms like RO and PR,  and confused by how adding TSV helps more than Jorrit using Protege.   Not sure I need to know these. 

I do know that the ParasiteTracker project has both direct and indirect products.  It is the first NSF-ADBC network with any dedicated funding (albeit small) to develop biotic associations. There will be some basic mechanisms/products that help develop other biotic interactions involving arthropods.  Probably the biggest indirect opportunity will be promoting pollinator-plant associations [#74] and more generally insect-plant associations.  But it would also be nice if this could promote parasitoid-parasite ontologies.

**Comment by diatomsRcool** [comment]
Sorry Neil. RO stands for Relations Ontology. Ideally, all the relations will be in one place rather than distributed across lots of ontologies. That way its easier for others to find and use. PR stands for Pull Request. If I did some work on an ontology and I was ready for it to be used, I would do a Pull Request, that alerts others to check my work before pushing the final button to merge my work with the rest of the ontology.
What Chris is suggesting is that rather than having Jorrit edit the ontology in Protege and have to do a pull request for others to review, we can set up a workflow that would allow someone with no knowledge of Protege (which can be a little clunky) to put the new terms in a simple file format, like TSV (tab separated), and an automated workflow would do all the work of updating, merging, and releasing the ontology with the new terms. If this workflow is already in place for the Relations Ontology, then its just a matter of adding the new terms to a TSV file. If this workflow is not already in place, then some non-trivial work needs to be done.
If you think that this project will only generate a few terms and you need to hurry up and get it done, then let's go with the Protege route as Jorrit suggests. If you anticipate that this project will generate lots of terms over years, then we should invest in the automated workflow.
@cmungall thoughts? We may be back to Jorrit needing guidance on RO procedures. Isn't there some documentation?

**Comment by seltmann** [comment]
We presently have some new classes and terms we know should be added to RO now (about 4 classes) and others that still need evaluation through the working group Jorrit is trying to start. Understanding a process for submitting them would go a long way to encouraging the working group activity.

I would also expect some kind of evaluation from RO curators for the new classes? I personally do not think it will be a lot (10-20?) because the focus on TPT project is arthropod museum specimens and museum specimen labels tend to not carry detailed relationship information. Of course, my hope is that the TPT group will get very excited and tackle some of the arthropod-vertebrate literature as well.

Thanks!

**Comment by nlharris** [comment]
What is the status of this?

**Comment by seltmann** [comment]
@nlharris @jhpoelen understands how to propose new terms and prepare pull requests, so we are able and understand how to move forward when we are ready. Thus, we think this issue can be closed. Thank you!

**Comment by nlharris** [comment]
Great, thanks!
