### ISSUE TITLE
'has effector activity' should not be a subclass of 'regulates' 

### ISSUE THREAD

**Issue by pgaudet** [oborel/obo-relations#347]
Hi @cmungall 

has effector activity http://purl.obolibrary.org/obo/RO_0002025 
should not be a subclass of 'regulates' 

It is 'downstream' of the regulatory activity: 

<img width="377" alt="image" src="https://user-images.githubusercontent.com/4782928/73834870-c202eb00-480c-11ea-9c20-fce6ecfd2ffc.png">

Thanks, Pascale

**Comment by dosumis** [comment]
On 5 Feb 2020, at 10:44, pgaudet <notifications@github.com> wrote:
> 
> Hi @cmungall <https://github.com/cmungall>
> has effector activity http://purl.obolibrary.org/obo/RO_0002025 <http://purl.obolibrary.org/obo/RO_0002025>
> should not be a subclass of 'regulates'
> 
> It is 'downstream' of the regulatory activity.
> 
> 

Don’t follow. Some background on the intent of these relations when I added them:

regulates is transitive.  P1 -- R -> P2 -- R -> P3  => P1--R -> P3  

Regulates chains can include MFs: 

MF1--directly_regulates ->  MF2

P 1—regulates-> MF1  —directly_regulates-> MF2 —directly_regulates-> P2  => P1—regulates—> P2

The point of has_effector_actitivty was to allow these chains to continue though compound MFs with regulatory and effector parts. Something like this:
 
Compound MF (CMF):
	 CMF  has_positive_regulatory_component PRC1 (a simple MF)
	 CMF  has_effector_activity EA1(a simple MF)
	(inferred from this is a positively_regulates relationship (or some sub-relation) Between EA1 and PRC1 

We might want to draw a GO-CAM with regulates (direct or not)  pointing to the whole CMF - or to PRC1 and with output from CMF or from PRC1.  In all cases we keep the transitive regulates chain.  Breaking these chains seems undesirable to me - as it would just be a function of how much detail was added to the GO-CAM model  - not of the biology.

Hth

**Comment by pgaudet** [comment]
Hi @dosumis 

Thanks for the feedback. But doesn't: 
> Compound MF (CMF):
	 CMF  has_positive_regulatory_component PRC1 (a simple MF)
	 CMF  has_effector_activity EA1(a simple MF)

mean that PRC1  -> directly positively regulates EA1? 

And if that's the case, then 
 
> (inferred from this is a positively_regulates relationship (or some sub-relation) Between EA1 and PRC1

should rather be a relation between PRC1 to EA1. Regulation is not reciprocal, right ?

**Comment by dosumis** [comment]
You're right.  I mis-typed.  should be :

inferred from this is a positively_regulates relationship (or some sub-relation) Between PRC1 and EA1

Should that be 'directly positively regulates?  Probably. It certainly feels right.  I avoided committing to this in the last post for two reasons - which might be irrelevant.  1. IIRC direct regulation is define in terms of physical interaction between the agents (proteins) that have MFs.  Does this cover the case where we have a single protein with regulatory and effector domains?  Perhaps this distinction is unimportant but 2. I seem to remember some problems for inference that came with using directly_positively_regulates in this context - perhaps to do with domain and range.

**Comment by pgaudet** [comment]
I just think the 'has effector activity' should NOT be under 'regulates, but only under 'has component activity'. The 'regulates' subclass should be removed.

**Comment by dosumis** [comment]
> I just think the 'has effector activity' should NOT be under 'regulates, but only under 'has component activity'. The 'regulates' subclass should be removed.

You're right. Sorry. It took  me some time to get my head back in the right place on this.   Great to see  you're  interested in these relations.  I  didn't do the best job of communicating my thinking  on  them at the  time.  Hope my summary here helped.

**Comment by pgaudet** [comment]
Great ! If you remove the 'regulates' subclasses then we are thinking to use 'has effector activity'  for compound functions. 

Thanks !

**Comment by dosumis** [comment]
I've just made this edit (see linked pull request)- but also remembered why this relationship is present:  It  allows  a  continuous chain of regulates relations  for  the  case

> Compound MF (CMF1):
> CMF1 has_positive_regulatory_component PRC1 (a simple MF)
> CMF1 has_effector_activity EA1(a simple MF)

P1 regulates -> CMF1
EA1 -> directly_regulates -> P2

Is sufficient  to infer P1 -regulates-> P2

This works because regulation of CMF1 => regulation EA1

So - may be  worth keeping  after  all - even if counter-intuitive at first?

**Comment by pgaudet** [comment]
OK, so what about cases where the effector function is not regulatory? Which relation should be used for that?

**Comment by dosumis** [comment]
> OK, so what about cases where the effector function is not regulatory? Which relation should be used for that?

Good question.

There is no inference that the effector function regulates anything downstream, just that CMF1 regulates EA1, and this is only relevant if someone makes a regulates link to CMF1

A picture might help:

![image](https://user-images.githubusercontent.com/112839/73937378-ceef0f80-48dc-11ea-8202-f1340d1d4135.png)

**Comment by dosumis** [comment]
Note - the full logic relies on inverses, which work for inference in GO-CAM but not in the ontology.

**Comment by pgaudet** [comment]
Thanks, the picture does indeed help ! 

The issue we encountered when we looked at GO-CAM models that were designed like you show above, is that we ended up stating that a protein was regulating its **own** activity, which curators did not agree with. 

Also this creates so many 'regulates' inferences that regulation becomes too ubiquitous - and while it's true that biology is all about regulation, we would like to express cases where one gene product's activity regulates the activity of another. 

We are looking for a relation where we will not infer regulation within a single gene product.

Thanks, Pascale

**Comment by dosumis** [comment]
You can have component functions that are not regulatory, but I can't see a where having CMF regulates ECF inferred under the hood causes problems as long as there is only one effector function per compound function (specified in the relation definition).  Even  if we don't know of any regulation right now, if someone finds that phsophorylation of the GP or complex that carries out  the CMF regulates its activity, don't you want the inference that this phosphorylation event regulates the effector function?

**Comment by thomaspd** [comment]
Just responding to David's point above, as I think we want to model things differently than you suggest above. My comments are in-line:

> I've just made this edit (see linked pull request)- but also remembered why this relationship is present: It allows a continuous chain of regulates relations for the case
> 
> > Compound MF (CMF1):
> > CMF1 has_positive_regulatory_component PRC1 (a simple MF)
> > CMF1 has_effector_activity EA1(a simple MF)
> 
> P1 regulates -> CMF1
> EA1 -> directly_regulates -> P2
> Is sufficient to infer P1 -regulates-> P2
I think that P1 regulates -> CMF1 should represent the effect of P1 on EA1 (the effector function of CMF1), not the effect on PRC1. This is consistent with the way David and I originally wanted to define compound functions: by their effector functions.
> 
> CMF1 has_effector_activity EA1
> +
> regualtes
> 
>     * has_effector_activity
>       =>
>       CMF1 regulates EA1
This seems to imply that regulation of CMF1 is equivalent to regulation of PRC1. But if we consider regulation of CMF1 to be equivalent to regulation of EA1 instead, we don't need to worry about bridging the causal gap between PRC1 and EA1. This would be more intuitive, I think, since it represents the causal effect on the last step in the internal, compound causal chain, and it is the effector function that will cause a change at the next step in the pathway. This also has the benefit of being consistent with how we've always defined effects on biological process (a chain of MFs) in terms of the output of the pathway (its final step(s)).
> 
> 
> So the regulates chain is not broken
> 
> So - may be worth keeping after all - even if counter-intuitive at first?

**Comment by dosumis** [comment]
Switching to (probably poorly remembered) CAMK as a more concrete example:

![image](https://user-images.githubusercontent.com/112839/73952953-93ae0a00-48f7-11ea-885f-b23c8d2f16bf.png)
(For clarity: all R in this figure are directly asserted, *not inferred*)

Would you expect GO-CAM models to always explicitly unfold kinase activity and make regulation links to this?   That might provide a solution for A -> D, but at the cost of forcing more cluttered GO-CAM models. 

But - isn't it fundamental to many compound functions that some regulatory subfunction regulates activity of the effector - Ca2+ binding in this case; ligand binding gating an ion channel... ?  Are you sure you don't want that inference either?  Would curators then need to record both B -R-> Ca2+ binfing activity and B -R-> kinase activity in the above case?

**Comment by pgaudet** [comment]
> But - isn't it fundamental to many compound functions that some regulatory subfunction regulates activity of the effector - Ca2+ binding in this case; ligand binding gating an ion channel... ? Are you sure you don't want that inference either? 

We don't *always* want that inference, so if it's encoded in the relation we don't have that flexibility.

**Comment by dosumis** [comment]
Sorry to be a pain and keep arguing.  I  feel it is important to make sure we have a common understanding here. Last questions (I promise) 

> > But - isn't it fundamental to many compound functions that some regulatory subfunction regulates activity of the effector - Ca2+ binding in this case; ligand binding gating an ion channel... ? Are you sure you don't want that inference either?

> We don't always want that inference, so if it's encoded in the relation we don't have that flexibility.

The inference requires two steps: 

1. The first one comes from has_regulatory_component.   If you don't want to record a component as regulatory, you can always choose simply has_component_activity
2. The second step is via has_effector_activity.  I considered it safe because of the rule that a compound function must have only one effector activity (this could be enforced by making the relation functional).  With this in place - anything that regulates CAMK must regulate its one effector function.  If you  want to record  regulation of other subfunctions (subactivities) you can connect your  regulates edge directly to that subfunction. If you don't want any inference to regulation of  the effector function, just make sure that subfunction is connected to the compound function via has_component_activity. 

***Do you have a counter example where this wouldn't work?***

It seems a shame to force curators to add lots of extra edges and nodes if they are not necessary.  And coming up with a set of rules to make sure everything gets wired up consistently seems hard to me.

**Comment by pgaudet** [comment]
> 1. (...) The first one comes from has_regulatory_component. If you don't want to record a component as regulatory, you can always choose simply has_component_activity

That should work. 


2. (...) anything that regulates CAMK must regulate its one effector function

Right - the activity of the upstream gene regulates the effector function. 
but the we would not consider that the component_activity would necessarily regulate the effector activity. 

Is that how that would work ? 

Thanks for your patience :)

**Comment by dosumis** [comment]
> (...) The first one comes from has_regulatory_component. If you don't want to record a component as regulatory, you can always choose simply has_component_activity
> That should work.
> 
> (...) anything that regulates CAMK must regulate its one effector function
> Right - the activity of the upstream gene regulates the effector function.
> but the we would not consider that the component_activity would necessarily regulate the effector activity.
> 

> Is that how that would work ?
> 

Yep.  You get the choice. You only use has_regulatory_component_activity* if you want  to infer regulation of the (single) effector function, otherwise just use has_component_activity*.

If  you do want that inference, besides giving you a concise way to record regulation, using has_regulatory_component activity, where it is biologically valid, allows you to record mechanisms of regulation of effector function.  In the CAMK case above (ignoring any argument about the biology  in  the   specific case)  you can record regulation of CAMK activity via regulation Ca2+ binding  (B -R—> CMAK activity)  as distinct from regulation via other mechanisms (A-R—> CMAK activity).  This GO-CAM is similar to what we used to call 'regulation of Ca2+ binding involved in regulation of CAMK activity’, but much more precise.

Here’s the complete set of component activity terms.





has_necessary_component_activity also infers ‘regulation’ under the hood.  This is for cases where a sub activity is necessary for an effector activity  - e.g. by providing  the energy that drives it.  Classic  examples are  ATPase-coupled transport.  This allows inference  that regulation of the  ATPase activity of an ATPase coupled Na2+ transporter will regulate the Na2+ transporter effector function.  (or as we used to record it: 'regulation of ATPase activity involved in regulation of Na2+ transporter activity’)
> Thanks for your patience :)
> 
No  worries. I  should have done a better job of  communicating it at the time.   The nice thing about  GO-CAMs is that they allow a clear visual representation of what we’re discussing and a clear way of presenting documentation.  Maybe we should have links from these relations to some official  GO doc with GO-CAM illustrations.

Cheers,
David

*current name in RO  - I think I’ve been using activity and function interchangeably in the names

**Comment by pgaudet** [comment]
> This allows inference  that regulation of the  ATPase activity of an ATPase coupled Na2+ transporter will regulate the Na2+ transporter effector function.

I dont think this is what we wanted. I'll check with @thomaspd @vanauken and @cmungall next week and get back to you. 

Thanks again !

Pascale

**Comment by pgaudet** [comment]
Hello @dosumis 

I looked at this again with @thomaspd and @balhoff and we need a term that describes an 'effector activity' that is not regulatory. 

Can you please remove the 'regulates' relation, and if needed for other purposes, create another term 'has 'effector activity' - would that work ? 

Thanks, Pascale

**Comment by dosumis** [comment]
OK I'll merge the [pull request](https://github.com/oborel/obo-relations/pull/348) first thing tomorrow

For the avoidance of doubt:

> we need a term that describes an 'effector activity' that is not regulatory.

*  We are not removing anything that infers the effector function regulates anything.  This is never inferred by the  current relation.

* We are removing an axiom that infers that anything that regulates a compound function regulates its effector function.  So,  X regulates 'CAMK activity'  => no implication of regulation of kinase activity if CAMK is modelled as a compound function that has_effector_activity kinase 'kinase activity'

This seems to be  consistent with what Paul said  he wanted  up  thread

For the case:

> > Compound MF (CMF1):
> > CMF1 has_effector_activity EA1(a simple MF)
> >  P1 regulates -> CMF1

Paul wrote:
> I think that P1 regulates -> CMF1 should represent the effect of P1 on EA1 

This is what the relation currently does, but will not do with the edit

**Comment by pgaudet** [comment]
> This is what the relation currently does, but will not do with the edit

OK sounds good ! Thanks @dosumis

**Comment by cmungall** [comment]
From my reading, the merge is unnecessary for the desired properties @pgaudet @thomaspd wants, and ends up removing desired properties.

@pgaudet - are there any bad inferences coming from this right now? Can we wait til we meet next week and discuss the merge then?

**Comment by pgaudet** [comment]
Sure

Le jeu. 27 févr. 2020 à 7:11 PM, Chris Mungall <notifications@github.com> a
écrit :

**Comment by balhoff** [comment]
In order to keep this:

>We are removing an axiom that infers that anything that regulates a compound function regulates its effector function. So, X regulates 'CAMK activity' => no implication of regulation of kinase activity if CAMK is modelled as a compound function that has_effector_activity kinase 'kinase activity'

Should this possibly be a property chain instead of happening via subpropertyOf?

`'regulates o 'has effector activity' -> regulates`

**Comment by dosumis** [comment]
> Should this possibly be a property chain instead of happening via subpropertyOf?
> 
> `regulates o 'has effector activity' -> regulates`

I  think that would work just as well.

**Comment by pgaudet** [comment]
Great !! Can we go ahead with this change then ? (ie merging this PR)

**Comment by cmungall** [comment]
Discussed this with @pgaudet. I think we are all good with @balhoff's proposal to use a property chain, @dosumis is too.

I will close the existing PR, and we will make a new PR for the chain
