### ISSUE TITLE
definition updates in the eco subset - referring to potentiality, and classes

### ISSUE THREAD

**Issue by jhammock** [oborel/obo-relations#363]
There is an elegant example of this in [has habitat](http://purl.obolibrary.org/obo/RO_0002303), defined as: "X 'has habitat' y if and only if: x is an organism, y is a habitat, and y can sustain and allow the growth of a population of xs."

I wonder if definitions of this form can be constructed for some of the other terms in the eco subset. We use some of these terms in EOL, (eg: eats, visits flowers of, parasitizes, etc.) with the intent of a similar construction. X and Y are classes, and the relationship can occur between instances of them. Would this conflict with how the terms are used in GloBI?

Thoughts, @jhpoelen , @diatomsRcool ?

**Comment by jhpoelen** [comment]
I very much support the idea of precise and unambiguous definitions of RO terms. I imagine that better definitions would encourage more appropriate term usage (if folks bother to read the definitions ; ) ).

For what it is worth: I am keeping a tabular list of RO term and their definitions at: 

https://github.com/globalbioticinteractions/nomer/blob/master/nomer/src/test/resources/org/globalbioticinteractions/nomer/match/ro.tsv

and I noticed that a bunch of terms need a definition or could do with a review of the definition.

I am curious to hear your plan on how to more forward on improving the RO definitions.

**Comment by jhammock** [comment]
I imagine it would be helpful to get a few eyes on any proposed definitions. Like I said, I was impressed by has_habitat. What do you think of that one? If it meets with your approval, I could attempt some provisional definitions in the style of has_habitat, in your lovely table, in a new column, and interested parties could discuss them here. 

I could send you a PR when I have something, or we could keep those napkin sketches in a separate, derivative table. What do you think?

**Comment by jhpoelen** [comment]
@jhammock I much like the way that has_habitat is defined. The ro.tsv table I referenced is derived from RO ontology. So rather than proposing / updating definitions in the derived table, why not edit the source owl file. These scary looking xml documents can be edited with a text editor. You can find existing definition by having a look at https://github.com/oborel/obo-relations/blob/e6384974d8cafc04aa9599d4018c6cce614fd026/ro-base.owl#L3395 -

```xml
<owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002209">
        <rdfs:subPropertyOf rdf:resource="http://purl.obolibrary.org/obo/RO_0002445"/>
        <obo:IAO_0000115>inverse of parasitoid of</obo:IAO_0000115>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/RO_0002259"/>
        <rdfs:label>has parasitoid</rdfs:label>
    </owl:ObjectProperty>
```

where ```<obo:IAO_0000115>inverse of parasitoid of</obo:IAO_0000115>``` is the part that captures the definition (compare with line #3 of derived ro.tsv in https://github.com/globalbioticinteractions/nomer/blob/9994eb3acd0725605f58cfe0d714d03771f3de3c/nomer/src/test/resources/org/globalbioticinteractions/nomer/match/ro.tsv#L3 ). 

If this approach appeals to you, I'd suggest to make one pull request for a single low-hanging-fruit definition update (has_host maybe?) and see how responsive the RO maintainers are.

**Comment by jhammock** [comment]
Thanks for the directions! That works for me. I'll do some homework and try a definition for a term that hasn't got one yet. We'll see...

**Comment by seltmann** [comment]
@jhammock I am also interested in getting definitions on RO terms. I also have a developing list of terms that are not in RO and I think could/should be.
