### ISSUE TITLE
Add pharmacological relations for small molecules

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#371]
Piggybacking on #369, could further small molecule pharmalogical relations be added like:

- has small molecule agonist 
- has small molecule antagonist
- has small molecule inverse agonist

**Comment by pgaudet** [comment]
It seems those represent narrow synonyms of the terms I created in #369 ?

**Comment by cthoyt** [comment]
I would say more sub-types than synonyms. The semantics of agonist, antagonist, and inverse agonist imply that the molecule is working on a receptor, while activator and inhibitor are usually used for things that aren't receptors (e.g., other proteins like enzymes, pathways, protein complexes)

**Comment by pgaudet** [comment]
OK - then also check 'has_ligand (RO_0002019)' because it refers to receptor: 

 definition: A relationship that holds between between a receptor and an chemical entity, typically a small molecule or peptide, that carries information between cells or compartments of a cell and which binds the receptor and regulates its effector function.

I realize pharmacologists use 'agonist' and 'antagonist', while in other fields 'ligand' is more widely used. In GO we have gone for 'ligand', using 'agonist' as a synonym. RO might prefer to use agnist/antagonist. In any case I don't think we should have both terms. 

Thanks, Pascale

**Comment by cthoyt** [comment]
Thanks for point that out. I have a two questsions:

1. How can the has_ligand relationship be used to differentiate endogenous (normally part of the biological system) and exogenous (stuff added to the system, like toxins or drugs) ligands?

I think generally, an agonist is an exogenous ligand that binds to the same place as the endogenous ligand and causes the same effect. An antagonist is an exogenous ligand binds to the sample place as the endogenous ligand and causes the opposite effect as the endogenous ligand.

It's most definitely the case that inverse agonists are only named in relation to the endogenous ligand - inverse agonists bind to a place that the endogenous ligand does _not_ bind, but causes the same effect as the endogenous ligand.

2. does the has_ligand relationship imply that the chemical modulates (either up or down) the activity of the receptor?

**Comment by cthoyt** [comment]
@matentzn this issue provides more context to the chebi chemical roles mapping we're doing [here](https://github.com/chemical-roles/chemical-roles) and more specifically about the mappings  between relations in that project, RO, and Wikidata that are listed [here](https://github.com/chemical-roles/chemical-roles/blob/master/src/chemical_roles/resources/relations.tsv)

**Comment by wdduncan** [comment]
Thanks @balhoff !

**Comment by cthoyt** [comment]
Thank you all for the nice feedback and helping get this through!
