### ISSUE TITLE
Generalise "developmentally related to"? 

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#449]
[developmentally related to](http://purl.obolibrary.org/obo/RO_0002324) is bound to [GO:developmental process](http://purl.obolibrary.org/obo/GO_0032502), which precludes ecosystemic, human, and other development processes - can a more general class be created?

I guess it's too far down the road to refactor this one, but perhaps the label can be sharpened.

xref e.g. #72 #73 #97 #229 #320 #323

**Comment by cmungall** [comment]
There are arguments for and against

 1. Generalizing the current hierarchy
 2. Creating a separate analogous hierarchy (possibly with very generic groupings)

@dosumis has provided good arguments in the past why 2 is good - we can have very crisp concrete definitions of developmental lineage in terms of cells.

If we go route 2 we have to make the existing labels reflect their more precise meaning to avoid confusion. I am not sure the best strategy.

 - prefixing with "ontogenetically"
 - inserting something like "cell lineage" into the term

**Comment by dosumis** [comment]
Generalising to include ecosystem and human development processes sounds a bit too much like smushing together concepts because of lexical similarity.  

Having a distinct set of ontogenetic developmental terms is useful.  These could be grouped by defining a general relation in terms of continuity of material (non transitive) and then defining a transitive parent property.  This ~ corresponds to the old RO derives_from (although the name elicited objections from evolutionary biologists).

**Comment by cmungall** [comment]
@dosumis this seems reasonable.

for the general relation, I would generalize even further and allow us to be able to specify continuity of spaces. In fact we already use develops from this way in uberon even though there is no cell lineage (various cavities have continutity, sometimes splitting, budding, and merging). I'm not convinced material vs immaterial is a useful way of subdividing the world for some domains like anatomy but that's another issue...
