### ISSUE TITLE
make in_taxon functional

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#459]
in_taxon has range 'organism' (at least implicitly) .  

Comment: Note - we could get the same reasoning results from disjointness axioms:  in_taxon some A DisjointWith in_taxon some B

see also https://github.com/oborel/obo-relations/issues/367

**Comment by matentzn** [comment]
Unfortunately, this is not possible in OWL.

(non-simple property in role chains violation)

We have two options:
1) we make the `only_in_taxon` functional:
![image](https://user-images.githubusercontent.com/7070631/116129543-22a46f00-a6c2-11eb-888c-bae1df33191e.png)
2) Introduce a shadow AP "functional" and make `in_taxon` functional like this - this requires a different reasoner to be used then.

**Comment by dosumis** [comment]
Where's the role chain? Is this just the property hierarchy?  

Don't think we care about 'only in taxon' any more.  Happy to make functional + maybe add a note that we now favour in_taxon instead and plan to obsolete at some point?

**Comment by matentzn** [comment]
![image](https://user-images.githubusercontent.com/7070631/116218322-532bed80-a742-11eb-86d4-99894c6aeb1b.png)

Lots of role chains. So the remaining question is this:

1. We make only-in-taxon functional and use that instead of in-taxon - everywhere
2. We leave as is, use `in-taxon` and not have it functional
     - we could add a QC check for anatomy ontologies that:
        1. Classifies the ontology and materialises `in-taxon`
        2. Strips out role chains and injects functional characteristic
        3. Classifies again
 3. Too much hassle for too little gain (close ticket, no action). 
 
 @dosumis you let me know how to proceed.

**Comment by cmungall** [comment]
@matentzn remember that the functional characteristic is not necessary if the taxon GCIs are included (i.e. in-taxon A DisjointWith in-taxon B, for all sib pairs AB). While this requires plumbling, the plumbing is in place, the GCIs are released with ncbitaxon - otherwise taxon constraints would not have worked for us in GO, Uberon, etc for the last decade!!!

It's on the OBO page for http://obofoundry.org/ontology/ncbitaxon

![image](https://user-images.githubusercontent.com/50745/117075983-8e9e5d00-acea-11eb-9fae-6806b3693631.png)

Makefile here:

https://github.com/obophenotype/ncbitaxon/blob/master/subsets/Makefile#L10-L11

So the choice is

 1. We make only-in-taxon functional and use that instead of in-taxon - everywhere
 2. We leave as is, use in-taxon and not have it be functional, and rely on GCIs being present

I don't think 3 (status quo) is a viable option.

Deciding between 1 and 2 is a complex engineering tradeoff. I prefer 2, it works with Elk/EL++. The downside is that the GCIs must be present and synced. Currently this is done as part of the NCBITaxon release, but it seems here institutional knowledge is slipping. Also we only do it for taxslim (which covers most taxa used in ontologies)

**Comment by matentzn** [comment]
Thank you @cmungall - sorry, forgot about the GCIs. 

I agree with your assessment and tend towards 2. Shouldnt these GCIs be shipped with RO (as they are effectively used to restrict the relation)? But I am happy either way. I want to use _only_ taxoslim from now on. Everywhere! 

Complete segway: One thing I noticed recently with @balhoff that you can actually exploit a minor flaw in DOSDP to Encode GCIs as background knowledge using the GCI section (with no variables) - basically what would happen in a generation scenario, is that the GCI is simply merged along with the rest of the pattern into OWL.

**Comment by dosumis** [comment]
I'm happy with the GCI solution . GCIs should live with ncbitaxonomy - maybe as an extension as I can imagine potential use cases for excluding.  Species hybrids exist (https://en.wikipedia.org/wiki/Liger) -are esp common in plants where sometimes fertile.

**Comment by cmungall** [comment]
Agree

**Comment by nlharris** [comment]
jim says: can't be functional (for every x, just one value of y) because involved in a lot of property chains.
issues due to implementation of OWL.

**Comment by balhoff** [comment]
We discussed at June 1 meeting and will not add the functional characteristic. Projects that want to implement taxon restrictions (we discussed CL) should import the disjoint-in-taxon axioms or use owltools to generate them.
