### ISSUE TITLE
NTR 'measurement method of' (previously in AgrO)

### ISSUE THREAD

**Issue by KrishnaTO** [oborel/obo-relations#535]
Hello,
I'd like to request adding [`measurement method of`](http://purl.obolibrary.org/obo/AGRO_00000253) to RO along with the following details:

`Label`: measurement method of
`Definition`: A relation between a plan specification and a 'specifically dependent continuant', in which the plan specification groups the specifically dependent continuant(s).
`Uses`: [area measurement protocol](http://purl.obolibrary.org/obo/AGRO_00000286), [material area density mesurement protocol](http://purl.obolibrary.org/obo/AGRO_00000242), [pivot lenght measurement protocol](http://purl.obolibrary.org/obo/AGRO_00000282), etc
`ORCID`: https://orcid.org/0000-0002-8461-9745

Can be a discussion if domains and ranges are needed.
[plan specification](http://purl.obolibrary.org/obo/IAO_0000104)
[specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020)

Originally a question in issue #505

@marieALaporte

**Comment by ddooley** [comment]
So this is a shortcut relation for something like "'plan specification' and 'executed by' some (assay and 'has specified input' some 'material entity') "?

I think if you are going to label it "measurement method of" then it would be great to reference a measurement process - probably an "assay" in the definition?

**Comment by KrishnaTO** [comment]
"'plan specification' and 'executed by' some (~~assay~~ 'planned process' and 'has specified input' some 'generically dependent continuant') 

'planned process' is sufficient IMO, where assay (subclass of 'planned process') requires some 'objective to produce information' which is just forces a grouping of classes.

`definition` [v2] - A relation between a 'plan specification' and a 'specifically dependent continuant', in which the 'plan specification' is carried out according to a 'planned process' that outputs a 'specifically dependent continuant'.

By this logic, it would be ideal to setup/use this relation only with a dosdp pattern, so that it forces a use of a 'plan specification' and 'planned process' with a 'specifically dependent continuant'.

**Comment by nlharris** [comment]
What remains to be done here?

**Comment by KrishnaTO** [comment]
If there aren't any issues from @ddooley or from one of the other RO experts, I think this term can be moved with the added definition. 

In which case, I can make a PR?

**Comment by matentzn** [comment]
Feel free! RO = community resource :)

**Comment by ddooley** [comment]
I do find the definition insufficient because it doesn't include the concept/semantics of measurement that the label "measurement method of" states.  On what basis are specifically dependent continuants being grouped?

**Comment by ddooley** [comment]
Can an example be spelled out too: an "area measurement protocol" is 'a measurement method of' an area.  Is that right?

**Comment by nlharris** [comment]
Is this now a change request rather than a new term request?

**Comment by cboelling** [comment]
I have difficulty understanding the proposed definition. What does "groups the specifically dependent continuant(s)" mean? Can examples be provided that illustrate the intent of the proposed relation?

**Comment by ddooley** [comment]
In Agro the relation "measurement method of" has a variety of uses:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/4000582/200347373-2421c637-a47c-4ea5-9000-5fdbf31d3c7d.png">

AgrO I think has an inverse "has method" with two axiomatizations:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/4000582/200345925-5767c657-1baa-4c75-a7a3-0a6bb867e094.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/4000582/200346279-a474860d-13c5-4134-a8cc-3fcaf1c6ea00.png">

I shy from using "method" in label because method is often construed as a process.

Seeing that the domain is of protocol, and the range is characteristic, a full label would be "measurement protocol of characteristic"  and its inverse: "characteristic has measurement protocol".

**Comment by wdduncan** [comment]
@KrishnaTO  I am unsure what you mean by
> outputs a 'specifically dependent continuant'

in 

> definition [v2] - A relation between a 'plan specification' and a 'specifically dependent continuant', in which the 'plan specification' is carried out according to a 'planned process' that outputs a 'specifically dependent continuant'.

Your proposed label includes the word 'measurement'. So, you are saying that the output is a [measurement datum](http://purl.obolibrary.org/obo/IAO_0000109)? If so, the range of the relation would be `(concretizes some measurement datum)`.  Or are there outputs other than measurement datums?

**Comment by wdduncan** [comment]
@KrishnaTO @ddooley  
Is there a case in which the measurement protocol/specification is not used during a planned process? If not, this may be an OBI issue. A `measurement protocol` would be a subtype of OBI's  [protocol](http://purl.obolibrary.org/obo/OBI_0000272) class, and `measurement process` could be defined as a `planned process` that `has_specified_input` some `measurement protocol`.

Also, RO doesn't include the class `plan specification`, which also makes me think this is something for OBI.

I'm not a fan of `executes` b/c it includes the property chain `realizes o concretizes` (see also:  https://github.com/OBOFoundry/COB/issues/217).

**Comment by ddooley** [comment]
@wdduncan OBI has been asked to critique this term/definition which we did yesterday. I forgot to mention above that this issue is about moving the AgroO relation to RO.  The requested relation appears always to attach between a "measurement protocol" and a characteristic.  Its a shortcut for having a protocol as part of a plan specification executed by a measurement process that is measuring some characteristic. I think COB would want to take on the "planned process" executes some "plan specification" axiom BECAUSE its in the definition of planned process?!
(Also planned processes execute protocols, rather than take them in as input).

I suggest starting from the most wordy version of the relation, and work back from there if smoother language can be accommodated, so, rather than "measurement method of" how about:

**label: measurement protocol of characteristic**
**definition:** An object property which attaches between a protocol part of a plan specification that is executed by a [measurement] process with the objective of measuring some characteristic of an entity.

I'm not sure we need to create a "measurement process" per se. since there is "assay", (but I see that measurement process is a bit more generic language).

**Comment by wdduncan** [comment]
Thanks @ddooley   
> Its a shortcut for having a protocol as part of a plan specification executed by a measurement process that is measuring some characteristic.

Do you have a specific example of usage you can share?

Also, part of what I don't like about the executes relation, is that linguistically we often speak of machines/people/agents executing plans. The process is what happens as a results of the agent carrying out the instructions. But, with the executes relation, it is the process that does the executing, not the agent. Anyway, that is topic for a different issue ...

**Comment by KrishnaTO** [comment]
> I think COB would want to take on the "planned process" executes some "plan specification" axiom BECAUSE its in the definition of planned process?!
(Also planned processes execute protocols, rather than take them in as input)

This is also AgrO's intended use, from my perspective (much to my unfortunate attempts to muddle the definitions before). 

> label: measurement protocol of characteristic

Need to involve @marieALaporte and/or @celineaubert for acceptance of label change into AgrO. 

> definition: An object property which attaches between a protocol part of a plan specification that is executed by a [measurement] process with the objective of measuring some characteristic of an entity.

> I'm not sure we need to create a "measurement process" per se. since there is "assay", (but I see that measurement process is a bit more generic language).

The addition of the intermediate `measurement process` or  the existing `assay` will require some additional relation updates in AgrO, but if I have it correct, the proposed `measurement process` will be:
1) `Area measurement protocol` equivalent to `measurement process` some `area measurement`. 
2) `area measurement` equivalent to `measurement method of` some `field area`

whereas currently, it is:
1) `Area measurement protocol` equivalent to  `measurement method of` some `field area`

**Comment by ddooley** [comment]
That last 'area measurement protocol' sentence is fine, we'd just be looking at a relabeling of the relation (if one accepts my opinion that method sounds too much like process rather than protocol):

`Area measurement protocol equivalent to '**measurement protocol of characteristic'** some field area`

Lets just assume "assay" for now, not add "measurement process".
Though I listed the expansion of the "measurement method of" relation, **I don't think AgrO needs to add that expansion to itself.**  Shortcuts don't necessarily have to be backed up with the expansion representation. Shortcuts are used when the expansion isn't needed.

The "equivalent to" has to have the same kind of entity on both sides, so:

`Area measurement protocol equivalent to measurement process some area measurement`

can't be right - a protocol is not a process.  A protocol is part of a plan specification which is executed by a process like an assay.

**Comment by wdduncan** [comment]
@KrishnaTO So, far I am only seeing very general examples about how some hypothetical measurement protocol is related to some hypothetical group of characteristics.   

It would be great if you had a specific experiment (i.e., use case) that you could provide as an example. This would be a great help (to me at least).

Are saying that the protocol is about some measurement process that measured one or more characteristics. In OWL, it would be something like this:
```
'measurement protocol' 'is about' some ('measurement process' that 'has input' some characteristic)
```
Or do you mean the protocol is about the characteristics? For example:
```
'measurement protocol' 'is about' some (characteristic that 'input of' some 'measurement process')
```

An example of usage would help make this clear.

**Comment by ddooley** [comment]
@wdduncan That first screenshot I gave above shows the examples taken directly from AGRO. As I understand it the way you link characteristics to a process is by way of recently introduced "regulates characteristic" rather than 'has input' some characteristic.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/4000582/201530792-914b908f-a822-43ee-bb56-9ad296430921.png">

The process changes characteristics of an input, rather than taking in characteristics as input directly.  So this "[protocol] 'measurement method of' some [characteristic]" just enumerates all the protocols that can measure something.  One might argue that the main interest is in enumerating all the processes that can measure some quality (with each process having a plan specification that mentions a protocol).  But if one is detailing protocols, and just having general names for the process, I get why this relationship is desired.

**Comment by wdduncan** [comment]
@ddooley Thanks for pointing me to the AgrO screen shots :)  
Sorry, if my previous comment was not clear. Hopefully, this helps ...

Using the mulch thickness example, here is a made-up example about mulch thickness using instances (it would be nice to have a real-world example).
```
:mulch-thickness#1 a :mulch-thickness
:mulch#1 a :mulch
:mulch-thickness#1 :inheres-in :mulch#1
```
And another made-up example about about an instance of a mulch thickness protocol:
```
:mulch-thickness-protocol#1 a :mulch-thickness-protocol
```

Here is the part I'm seeking clarity about.

I assume that `:mulch-thickness-protocol#1` implicitly related to a measurement process, which I will represent as an anonymous individual `_:mp`. Now how does `_:mp` relate to `:mulch-thickness#1`?

Option 1: Using an anonymous measurement datum:
```
_:mp a :measurement process

# I'm not a fan realizing concretizations (i.e., 'executes'), but substitute that here if it helps your understanding
_:mp :has-participant :mulch-thickness-protocol#1  

_:mp :has-specified-input :mulch#1 
_:mp :has-specified-output _:measurement-datum
_:measurement-datum :is-about :mulch-thickness#1 
```

Option 2: The protocol is about the measurement process:
```
_:mp a :measurement process
_:mp :has-specified-input :mulch#1 
:mulch-thickness-protocol#1  :is-about _:mp  # no measurement datum involved here
```

Option 1 makes more sense to me. But, I might not be understanding the intent of how the protocol relates to the characteristic.

Also, note that the axiom `'mulch thickness' Subclass Of 'has method' some 'mulch thickness measurement protocol'` is too strong. It assert that every instance of `mulch thickness` is related to an instance of `mulch thickness measurement protocol`. Surely, there are instances of `mulch thickness` that are not so related.

**Comment by wdduncan** [comment]
@ddooley   
> As I understand it the way you link characteristics to a process is by way of recently introduced "regulates characteristic" rather than 'has input' some characteristic.

The `regulates characteristic` doesn't seem right to me. Not sure what it means for a protocol (or measurement process) to `results in the existence of C  OR affects the intensity or magnitude of C`, where `C` is a characteristic.

**Comment by ddooley** [comment]
@wdduncan I like #1.  

Side note, OBI has your "_:mp :has-participant :mulch-thickness-protocol" structured as "_:mp executes (':plan specification' and 'has part' :mulch-thickness-protocol)"

"regulates characteristic" doesn't apply to measurement processes for domain. I meant that only as an aside about existing way for some processes to "note" the characteristics of materials they change. A heating water process affects the temperature characteristic (of water).

I think the use of having a list of protocols connected to the characteristics they (through measurement processes) generate datums on shows up where one has a choice of how to measure something, e.g.

- thermometer measurement protocol
- cold/warm/hot finger sensation protocol
- thermal imaging protocol
...

**Comment by wdduncan** [comment]
> Side note, OBI has your ":mp :has-participant :mulch-thickness-protocol" structured as ":mp executes (':plan specification' and 'has part' :mulch-thickness-protocol)"  

I was not aware that the `executes` relation had made its way into OBI. I couldn't find it in the 2022-07-11 version. If it is the same as the [STATO:executes](https://ontobee.org/ontology/STATO?iri=http://purl.obolibrary.org/obo/STATO_0000102) relation, then it unfortunately (in my opinion) is defined by the property chain `realizes o concretizes`.


> @wdduncan I like # 1.


So do I :)  
However, we need a different label than `has method`. For now, let's call it `foo`. The definition for `foo` might go something like this (adapted from IAO [ is quality measurement of](http://purl.obolibrary.org/obo/IAO_0000221)):

> x **foo** y means x is a measurement protocol, y is a characteristic, and there is a measurement process that uses/utilizes x to output a measurement datum that is about y.

How does that sound?

Some possible labels for `foo`?:
- `measurement protocol defines characteristic` (or its inverse characteristic `defined by measurement protocol`)
- `defines measurement of characteristic`
- `specifies measurement of characteristic`

What labels do you suggest?

**Comment by ddooley** [comment]
@wdduncan Oh brother- I overstepped.  I forgot "executes" is coming from COB which is as you say coming from STATO.

Yes, your defn. sounds fine!

Names names names. 
measurement protocol mentions characteristic (in line with existing "mentions" RO relation)
measurement protocol about characteristic (info doc is allowed to be about one or more things?)
hmm.

**Comment by wdduncan** [comment]
@ddooley yes names are a pain :(

Does `measurement protocol` need be in the name, or can we short just `protocol`? If so (to build of your examples), how about `protocol about measurement of characteristic`?

Also, if we want domain/range constraints, we would need to `protocol` and `characteristic` to RO. Will this be an issue?

**Comment by ddooley** [comment]
"protocol about measurement of characteristic" sounds fine to me.  @KrishnaTO ?

Can't speak for RO, but I'd think given how core the process model is, that they'd be welcome.

**Comment by wdduncan** [comment]
One last suggestion (hopefully). I think it may be advantageous to generalize the relation to:
- `about measurement of characteristic`
- domain: `generically dependent continuant`
- range: `characteristic`

This still satisfies the use case, but will also allow for other things that may be about the "measurement of characteristic"

**Comment by wdduncan** [comment]
@KrishnaTO @ddooley Please the definition I created for `is about measurement of characteristic` in PR https://github.com/oborel/obo-relations/pull/655.

```
x is about measurement of characteristic y means that 
 - x is an information content entity
 - y is a pato:quality (characteristic)
and there is a process that utilizes x to output information that is about y.
```
Is this what you are wanting?

I also have a very similar term named `is characteristic measurement of` with definition:
```
x is characteritic measurement of y means that:
  - x is an information content entity
  - y is a pato:quality (chacteristic)
and x is about the measurement of y.
```
From what I recall, `is characteristic measurement of` is **not** what you were looking for. Right?

**Comment by wdduncan** [comment]
@jamesaoverton Based on the discussion so far, the request was for relating protocols to characteristics. The intervening process is mentioned in the proposed definition for `is about measurement of characteristic`.

```
x is about measurement of characteristic y means that 
 - x is an information content entity
 - y is a pato:quality (characteristic)
and there is a process that utilizes x to output information that is about y.
```

However, if they prefer to use assays instead, I can close the PR.

**Comment by KrishnaTO** [comment]
> @KrishnaTO @ddooley Please the definition I created for `is about measurement of characteristic` in PR #655.
> 
> ```
> x is about measurement of characteristic y means that 
>  - x is an information content entity
>  - y is a pato:quality (characteristic)
> and there is a process that utilizes x to output information that is about y.
> ```
> 
> Is this what you are wanting?
> 
> I also have a very similar term named `is characteristic measurement of` with definition:
> 
> ```
> x is characteritic measurement of y means that:
>   - x is an information content entity
>   - y is a pato:quality (chacteristic)
> and x is about the measurement of y.
> ```
> 
> From what I recall, `is characteristic measurement of` is **not** what you were looking for. Right?

No, unfortunately the latter definition creates too generic and not-in-line relation between any information content entity and a characteristic, but this relation is focused on the protocols. This brings up a good discussion on whether the domain can be generalised from protocol to information content entity, and my opinion is no since we are aiming to use `**protocol** about measurement of characteristic`.
In the existing relations of AgrO, each of the `protocol about measurement of characteristic` [changed from `measurement method of`] links to more generic characteristic measurements, where some protocols have multiple characteristic measurements and some which currently have one. Early thinking for this was very likely as @ddooley mentioned:

> I think the use of having a list of protocols connected to the characteristics they (through measurement processes) generate datums on shows up where one has a choice of how to measure something

--- 

> I think I understand the motivation behind this request, and agree that it's important to get it sorted out. I'm working on a proposal to more clearly link characteristics to the processes that measure them: https://github.com/jamesaoverton/qqv. I think that work is relevant to this discussion, or at least would help clarify the intent here.

> As an OBI developer, I think that it's more useful to talk about assays (and types of assays) than about protocols. One reason is that we have more than a thousand assay terms defined, and would not like to create a shadow hierarchy of protocols for every assay type.

@jamesaoverton I also think that although assays have some standing, the intention here was to link, the more generalised, characteristics to protocols. I agree with you that links between assays and entities can provide more immediately practical relations, but this relation was definitely targeting more abstract characteristic measurement relations. I think a move towards the qqv model may be warranted, but these legacy relations will also help to frame explicit relations between entity-characteristics.

**Comment by wdduncan** [comment]
@KrishnaTO 
> my opinion is no since we are aiming to use **protocol** about measurement of characteristic.

In AgrO, you can create a more specific `protocol about measurement of characteristic` with domain `protocol`  that is a child of `is about measurement of characteristic`. IMHO, RO needs to stay as general as possible, and `protocol about measurement of characteristic` would require more of the `ICE` branch in OBI to be imported. I am trying to keep the number of classes in RO to a minimum.

**Comment by jamesaoverton** [comment]
@ddooley:

1. I do see the need for OBI 'assay' to point to the characteristic that it measures. I don't like the label "senses" and I don't see why we need a 'sensing (measurement) process'. 
2. I would really like a technical definition/elucidation of "shortcut" relation. Does this mean an OWL Object Property defined using a property chain? If so, what is the chain being proposed?

Two clarification questions for @KrishnaTO: 

1. You provides some links to 'measurement method of' but none of them work for me. Is that an existing AgrO term? If so, what is the PURL?
2. The practical point here is that AgrO made a modelling choice to have many subclasses of OBI ['protocol'](https://ontobee.org/ontology/AGRO?iri=http://purl.obolibrary.org/obo/OBI_0000272) but no subclasses of OBI ['assay'](https://ontobee.org/ontology/AGRO?iri=http://purl.obolibrary.org/obo/OBI_0000070). So it would be convenient to have a link between the characteristic and the protocol. Right?

**Comment by ddooley** [comment]
@jamesaoverton about 1 I think assay works for AGRO use case.  Bill noted that assay has only material entity for input.  If we wanted to measure characteristics for other kinds of input like processes, then we couldn't use assay.  Hence a more general "measurement process" would be needed.
About 2 yes, in this case shortcut represents an object property chain.  
- whatever you may prefer for "senses" it would be [process] has specified output o is about [characteristic]
- If AGRO still wanted "is about measurement of characteristic" it would be [protocol] executed by o senses [characteristic]

**Comment by ddooley** [comment]
@jamesaoverton Instead of "senses" perhaps "measures"?  But then I look at the long list of assays and think they are doing more than measuring a characteristic.  The sequencing ones seem to "**represent**" a characteristic? Defn. molecular sequencing: "An assay the uses chemical or biochemical means to infer the sequence of a biomaterial".  (This sense of characteristic seems a bit odd to me tho, its a compendium of measures of each molecular position.)

**Comment by KrishnaTO** [comment]
@wdduncan 
> In AgrO, you can create a more specific protocol about measurement of characteristic with domain protocol that is a child of is about measurement of characteristic. ...protocol about measurement of characteristic would require more of the ICE branch in OBI to be imported.

This is an attractive option for AgrO, in order to keep work down, but still keep RO relations. 

@ddooley
> ...Then AGRO could simply query for all protocols linked to a measurement process that senses a characteristic. This assumes protocols are being linked to an appropriate measurement process.

If AgrO goes ahead with this model, it would definitely create a nice linkage between processes and protocols. 

@jamesaoverton
> You provides some links to 'measurement method of' but none of them work for me. Is that an existing AgrO term? If so, what is the PURL?

There was a recent release where the property was removed to satisfy the OBO dashboard requirements of using RO properties only. It is present in last month's release, found here with the mentioned PURL: https://github.com/AgriculturalSemantics/agro/releases/tag/v2022-10-18

> The practical point here is that AgrO made a modelling choice to have many subclasses of OBI ['protocol'](https://ontobee.org/ontology/AGRO?iri=http://purl.obolibrary.org/obo/OBI_0000272) but no subclasses of OBI ['assay'](https://ontobee.org/ontology/AGRO?iri=http://purl.obolibrary.org/obo/OBI_0000070). So it would be convenient to have a link between the characteristic and the protocol. Right?

Well, AgrO did create a sibling under `planned process`, [agricultural process](http://purl.obolibrary.org/obo/AGRO_00002071), to capture a lot of similar classes. I think it may have been a timing and disconnect issue because AgrO has been worked upon for quite some time. The issue arises where existing literature and program knowledge comes in, as concepts exist which are being used whether it is semantically essential or not, requiring AgrO to capture those classes for the application which relied on this ontology.

**Comment by jamesaoverton** [comment]
@KrishnaTO I apologize for getting off topic, but OBO terms should never just be deleted. If <http://purl.obolibrary.org/obo/AGRO_00000253> was published, you can mark it as obsolete, but it should still be included in the OWL file so that PURL can resolve. This is how we support legacy data.

If you define non-RO relations, the OBO Dashboard will have a blue "i". That's still a pass. If all those non-RO relations are obsolete, you should get a green check. None of the Dashboard checks are meant to encourage terms to be deleted.

**Comment by wdduncan** [comment]
@ddooley  
> @jamesaoverton Instead of "senses" perhaps "measures"?  

I was thinking that senses/measures would be in AgrO specific relation. RO would only house the more general `about measurement of characteristic` relation. Did you want senses/measure to be in RO?

@jamesaoverton 
> I'd appreciate some time to make an alternative proposal to address this use case.

Not trying to pressure you, but have had time work on this? It would be good if this issue can be closed soon.

**Comment by jamesaoverton** [comment]
I don't think this issue is close to resolution. AgrO had a term that was doing what they wanted. They deleted it, apparently because of a miscommunication about what the OBO Dashboard check for Principle 7 means. If a new term is going to go into RO and be reused by a wider range of ontologies, then it should fit existing modelling for the affected ontologies, including OBI and IAO. The proposed PR also imports a sizeable chunk of IAO into RO for the first time. IAO already imports RO, creating a circularity that I'm concerned about.

We discussed this issue for 30 minutes on the OBI call last week. I am not the only person with concerns about it. I'm just the one who is taking the time to lay out the problems.

**Comment by ddooley** [comment]
Senses/measures wouldn't be AGRO specific.  Its very general, applying to any process generating measurement datums about characteristics. @jamesaoverton do you agree? I'd love if you suggested a name for this.

Crucially, AGRO may no longer need "measurement method of" or "is about measurement characteristic of" if we get this senses/measures relation added.  AGRO is in a position to structure their database as protocol -> measurement process -> senses/measures characteristic, so they'd add some general measurement processes to group things and make for easier querying.  Is that right @KrishnaTO ?

**Comment by KrishnaTO** [comment]
> Crucially, AGRO may no longer need "measurement method of" or "is about measurement characteristic of" if we get this senses/measures relation added. AGRO is in a position to structure their database as **protocol -> measurement process -> senses/measures characteristic**, so they'd add some general measurement processes to group protocols by and make for easier querying. Is that right @KrishnaTO ?

It would definitely improve the querying and encase the generalised protocols for the varied methods, IMO.

@marieALaporte

**Comment by wdduncan** [comment]
@jamesaoverton  
Thanks for your input. I really appreciate it. It would be nice if specific examples of how adding this relation would affect other ontologies could be given. Right now, the push back against this seems vague, and the major theme of the push back seems to be that OBI doesn't like it. If others besides you disagree, it would be helpful to hear from them too.

I proposed on IAO issue tracker  to move `is about` to RO ([issue](https://github.com/information-artifact-ontology/IAO/issues/264)). However, the sentiment in IAO  seems to be that `is about` should be left where it is. I disagree that importing IAO `is about` (and its few children) would cause problems. But, doing this may be moot if this issue can't be resolved.

@KrishnaTO @ddooley This ticket has been open for nearly a year. I would be great if you could meet with @jamesaoverton (and whoever else has concerns about this ticket) to reach a resolution. I have heard complaints from others that getting relations into RO takes too long and is too hard. If the resolution is to close this issue, I am fine with that. My involvement on this issue is mainly to help move RO along in a more efficient manner.

There also seems to be a larger underlying issue of whether RO should house every relation in the Foundry. But, that is something better discussed in a separate issue (or on a call).

**Comment by ddooley** [comment]
Lets close this in favour of https://github.com/oborel/obo-relations/issues/658

**Comment by wdduncan** [comment]
I closed the associated PR.
