### ISSUE TITLE
General guidance for part_of and overlaps

### ISSUE THREAD

**Issue by shawntanzk** [oborel/obo-relations#564]
Need to add guidance on direction of terms:

Overlaps: try to follow small to large 
part_of: try to use this instead of has_part unless has_part is required for definition

**Comment by cmungall** [comment]
> Overlaps: try to follow small to large

where did this come from? Is overlaps even a priority to assert? I would like to see more anatomy ontologies be spatially JEPD but this is a long term goal.

> part_of: try to use this instead of has_part unless has_part is required for definition

hmm, I think there is a lot to unpack here. there is underlying assumption of subClassOf-all-some here, yes

1. the overarching guideline is that the axioms MUST be true and SHOULD be reasonably complete
2. this should also be guided by what the users of ontologies find useful.

For anatomy ontologies, your rule of thumb turns out to be conformant with both. part-of is the predominant direction because things vary more in their composition that where they are found. and it is most useful for the fundamental use cases of an anatomy ontology such as propagating genes upwards.

However, for protein complex ontologies, this is reversed.

One way or another we need more documentation of this sort. I think that uberon should contain the over-arching guidelines for anatomy, other domain ontologies should include guidelines and patterns for their domain. And RO should include more high level guidelines and link out to domain guides.

But this is hard to coordinate and I am open to RO housing domain-specific guidelines for now if people want to write them!

**Comment by shawntanzk** [comment]
closing this ticket as it is replaced by one in uberon: https://github.com/obophenotype/uberon/issues/2253
