### ISSUE TITLE
add parasitoidOf / hasParasitoid 

### ISSUE THREAD

**Issue by jhpoelen** [oborel/obo-relations#81]
suggest to add (endo|ecto) parasitoidOf / has (endo|ecto) parasitoid of as subtype of parasiteOf/ hasParasite. 

see https://github.com/mangal-wg/mangal-standalone/commit/cd2f985fbfbb126114ac5f71576083243099b799#diff-c5c7912985956937025d37d338764d7bR22 and https://github.com/jhpoelen/eol-globi-data/issues/81#issuecomment-147560132 for context

**Comment by cmungall** [comment]
would you/others agree with the def of a parasite that kills or sterilizes its host?

https://en.wikipedia.org/wiki/Parasitoid#Definitions_and_distinctions

**Comment by jhpoelen** [comment]
@jhammock @tpoisot any thoughts on the proposed definition for parasitoid?

**Comment by tpoisot** [comment]
Well in fact I might as well submit a PR for the whole range of mangal interactions: https://github.com/mangal-wg/mangal-schemes/blob/master/schemes/interaction.json#L44

And I realize that it might need adding some allowed values in mangal.

This will take a few days.

**Comment by tpoisot** [comment]
(This will also replace #80) -- where should I start (i.e. in what file)?

**Comment by cmungall** [comment]
Depends how you want to do this. You could fork this repo and edit ro-edit.owl. However, we still suffer from this problem: http://douroucouli.wordpress.com/2014/03/30/the-perils-of-managing-owl-in-a-version-control-system/ -- the owlapi and protege developers *almost* have this fixed.

The way we often do this is that you would "lock" the file. (This is purely a social mechanism, just say when you want to edit, the RO editors will hold off, and won't edit until we've merged the PR)

Oh, you'd also need an ID range in Protege

If this just sounds like way too much hassle I'm open to pretty much anything - an excel file of relations, a made-up yaml file, tickets, ...

how do you want to be credited: orcid, github username, publication...?

**Comment by tpoisot** [comment]
I'm fine working on whatever format will be easiest to integrate on your size, as long as it is reasonably documented. How do I get, e.g., an ID range in Protege?

And what kind of credit mechanisms do you have (this is where the DOI idea in #83 came from, in part)?

I'll just *lock* the file when I am ready to work on the PR. Still need to figure out the format, etc, before.

**Comment by cmungall** [comment]
On Tue, Oct 20, 2015 at 6:46 PM, Timothée Poisot <notifications@github.com>
wrote:

> I'm fine working on whatever format will be easiest to integrate on your
> size, as long as it is reasonably documented. How do I get, e.g., an ID
> range in Protege?
>
Added one for you (you're not compelled to use it if this turns out to be
too convoluted)
https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-idranges.owl

You still need to assign this range in Protege (its not smart enough to
read the file, which is currently only read by humans). I think this may be
the best docs we have:
http://obofoundry.github.io/docs/SettingUpProtege.html


> And what kind of credit mechanisms do you have (this is where the DOI idea
> in #83 <https://github.com/oborel/obo-relations/issues/83> came from, in
> part)?
>

It's not completely uniform across ontologies, and sometimes inconsistently
applied within them, but we try and err on the side of inclusivity. Have a
look at some existing entities in RO in Protege. Roughly, add yourself as a
contributor, and include a source for the definition: some external
reference, website, yourself, a colleague, etc


> I'll just *lock* the file when I am ready to work on the PR. Still need
> to figure out the format, etc, before.
>

OK. I recommend the pizza tutorial. Bit of a learning curve just to add
some relations but you may find it interesting... or not! Let us know how
you get on

**Comment by jhpoelen** [comment]
@cmungall related to the original topic of this issue, from Malcolm Story regarding your proposed definition of parasitoid. Given this an no objection from others, I'd say that we should adopt your proposed definition.

Please close this issue once the parasitoid related interactions are available.

Thanks!
-------
[...]
Returning to topic: the addition of sterilisation is new to me but makes sense in a Darwinian way – ie a parasite reduces fitness, a parasitoid reduces fitness to zero & a mutualist/symbiont increases fitness. It gets over the problem of what resource a parasite takes (as these are nutrition concepts, I’d always thought in terms of energy but then you rarely get symbiosis cos energy transfer is generally one way in a symbiotic interaction. )
 
Yes, I like it! I’ll update my definitions.
[...]

**Comment by jhpoelen** [comment]
Also used by iNaturalist http://www.inaturalist.org/observation_fields/4146 . @cmgunall Please let me know if there anything that is preventing this term from entering RO.
